# =============================================================================
# RetailMart AI Analytics - Fallback & Degradation Strategy
# =============================================================================
"""
Graceful degradation when primary LLM fails.
Fallback chain: Primary Model → Smaller Model → Pre-computed Answers → Error Message
"""

import logging
from typing import Optional
from config import get_settings

logger = logging.getLogger(__name__)

# Pre-computed answers for common questions (last resort)
PRECOMPUTED_ANSWERS = {
    "revenue": {
        "answer": "For revenue data, please check the Executive tab of the dashboard which shows total revenue, 30-day revenue, and growth metrics. You can also query `analytics.mv_executive_summary` directly.",
        "sources": ["analytics.mv_executive_summary"],
    },
    "top products": {
        "answer": "You can find top products in the Products tab. The data comes from `analytics.mv_top_products` which ranks all products by revenue. The top 20 products are shown by default.",
        "sources": ["analytics.mv_top_products"],
    },
    "top customers": {
        "answer": "Customer rankings by lifetime value are available in the Customers tab. Check `analytics.mv_customer_lifetime_value` ordered by total_revenue DESC for the full list.",
        "sources": ["analytics.mv_customer_lifetime_value"],
    },
    "churn": {
        "answer": "Churn risk customers are tracked in `analytics.vw_churn_risk_customers`. The view shows customers inactive for 30+ days, prioritized by their tier and inactivity duration.",
        "sources": ["analytics.vw_churn_risk_customers"],
    },
    "delivery": {
        "answer": "Delivery performance is tracked monthly in `analytics.vw_delivery_performance`. Key metrics include on-time delivery %, average delivery days, and SLA status.",
        "sources": ["analytics.vw_delivery_performance"],
    },
    "alerts": {
        "answer": "Active business alerts can be found in `analytics.vw_all_active_alerts`. This includes critical stock alerts, churn risks, revenue anomalies, delayed shipments, and high return rates.",
        "sources": ["analytics.vw_all_active_alerts"],
    },
}


class FallbackChain:
    """Implements a multi-tier fallback strategy for LLM failures."""

    @staticmethod
    def handle(question: str, original_error: str) -> dict:
        """
        Try fallback options in order:
        1. Retry with a smaller/cheaper model
        2. Match to pre-computed answers
        3. Return a helpful error message
        """
        # Tier 1: Try with fallback model
        tier1_response = FallbackChain._try_fallback_model(question)
        if tier1_response:
            logger.info("Fallback Tier 1 succeeded (smaller model)")
            return tier1_response

        # Tier 2: Match to pre-computed answers
        tier2_response = FallbackChain._try_precomputed(question)
        if tier2_response:
            logger.info("Fallback Tier 2 succeeded (pre-computed answer)")
            return tier2_response

        # Tier 3: Helpful error message
        logger.warning("All fallback tiers exhausted")
        return FallbackChain._error_response(question, original_error)

    @staticmethod
    def _try_fallback_model(question: str) -> Optional[dict]:
        """Try generating an answer with a smaller, cheaper model."""
        settings = get_settings()

        if not settings.enable_fallback:
            return None

        try:
            from langchain_google_genai import ChatGoogleGenerativeAI
            from langchain_core.messages import SystemMessage, HumanMessage
            from ai.prompts import SYSTEM_PROMPT

            llm = ChatGoogleGenerativeAI(
                model=settings.fallback_model,
                api_key=settings.gemini_api_key,
                temperature=0.1,
                max_tokens=500,
                timeout=10,
            )

            response = llm.invoke([
                SystemMessage(content=SYSTEM_PROMPT + "\n\nIMPORTANT: Provide a brief, helpful answer. If you need SQL data, suggest which analytics view to query."),
                HumanMessage(content=question),
            ])

            return {
                "answer": response.content.strip() + "\n\n_⚠️ Note: This response was generated by a fallback model and may be less detailed._",
                "sql_query": None,
                "data": None,
                "confidence": 0.4,
                "sources": [],
                "tokens_used": response.usage_metadata.get("total_tokens", 0),
                "latency_ms": 0,
                "model_used": settings.fallback_model + " (fallback)",
                "cached": False,
            }

        except Exception as e:
            logger.warning(f"Fallback model also failed: {e}")
            return None

    @staticmethod
    def _try_precomputed(question: str) -> Optional[dict]:
        """Match question to pre-computed answers using keyword matching."""
        question_lower = question.lower()

        for keyword, data in PRECOMPUTED_ANSWERS.items():
            if keyword in question_lower:
                return {
                    "answer": data["answer"] + "\n\n_ℹ️ This is a pre-computed response. The AI service is temporarily unavailable._",
                    "sql_query": None,
                    "data": None,
                    "confidence": 0.3,
                    "sources": data["sources"],
                    "tokens_used": 0,
                    "latency_ms": 0,
                    "model_used": "pre-computed (fallback)",
                    "cached": False,
                }

        return None

    @staticmethod
    def _error_response(question: str, original_error: str) -> dict:
        """Final fallback — helpful error message."""
        return {
            "answer": (
                "I'm sorry, I'm currently unable to process your question due to a "
                "technical issue. Here are some things you can try:\n\n"
                "1. **Rephrase your question** — try being more specific\n"
                "2. **Check the dashboard** — the 7 tabs have pre-computed analytics\n"
                "3. **Try again in a few minutes** — this may be a temporary issue\n\n"
                "Common questions I can answer:\n"
                "- 'What was our total revenue last month?'\n"
                "- 'Who are our top 10 customers?'\n"
                "- 'Which products have the highest return rates?'\n"
                "- 'How are our stores performing by region?'\n"
            ),
            "sql_query": None,
            "data": None,
            "confidence": 0.0,
            "sources": [],
            "tokens_used": 0,
            "latency_ms": 0,
            "model_used": "none (error fallback)",
            "cached": False,
        }
